FROM registry.access.redhat.com/ubi9/python-311
WORKDIR /app

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir --upgrade boto3==1.36.26 \
                                         kfp==2.11.0

COPY app.py .
COPY app.yaml .

USER 1001

CMD ["python", "./app.py"]
