apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: <imageStream>
  namespace: <namespace>
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: <buildConfig>
  namespace: <namespace>
spec:
  triggers:
    - type: ConfigChange
  source:
    contextDir: builds/
    type: Git
    git:
      uri: https://github.com/tarolive/demo-irpf.git
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile.<containerfile>
  output:
    to:
      kind: ImageStreamTag
      name: <imageStream>:latest
