FROM registry.redhat.io/ubi9/python-311
WORKDIR /app

USER root

RUN dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm && \
    dnf -y update && \
    dnf -v repolist && \
    dnf -y --enablerepo=rhel-9-optional-rpms --enablerepo=rhel-9-extras-rpms install tesseract

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir --upgrade pandas==2.2.3 pytesseract==0.3.13

USER 1001
