FROM python:3.11-slim
WORKDIR /app

RUN apt-get update && \
    apt-get -y install tesseract-ocr

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir --upgrade pandas==2.2.3 pytesseract==0.3.13

USER 1001
